//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

@class NSMutableDictionary;

@interface _UXButton : NSButton
{
    NSMutableDictionary *_titlesByState;
    NSMutableDictionary *_titleAttributesByState;
}

- (void)tintColorDidChange;

- (void)setTitleAttributes:(NSDictionary * _Nullable)attributes forState:(unsigned long long)state;

- (void)setTitle:(NSString * _Nullable)title forState:(unsigned long long)state;

@end

