//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

@class NSMutableDictionary;

@interface _UXButton : NSButton
{
    NSMutableDictionary *_titlesByState;
    NSMutableDictionary *_titleAttributesByState;
}

+ (Class)cellClass;
- (void)cxx_destruct;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)_textColorForState:(unsigned long long)state;
- (id)_AttributedStringForState:(unsigned long long)state;
- (void)setTitle:(NSString *)title;
- (void)mouseUp:(id)up;
- (void)viewWillMoveToSuperview:(UXView *)superView;
- (void)tintColorDidChange;
- (void)setTitleAttributes:(NSDictionary *)attributes forState:(unsigned long long)arg2;
- (void)setTitle:(NSString *)title forState:(unsigned long long)arg2;
- (id)initWithFrame:(CGRect)frame;

@end

