//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

@interface _UXButtonCell : NSButtonCell
{
}

- (unsigned long long)_controlState;
- (void)drawImage:(NSImage *)image withFrame:(CGRect)frame inView:(NSView *)view;
- (CGRect)drawTitle:(NSString *)title withFrame:(CGRect)frame inView:(NSView *)view;

@end

