//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@import  AppKit;

@class NSIndexPath, NSString;

@interface _UXCollectionViewItemKey : NSObject <NSCopying>
{
    unsigned long long _hash;
    NSIndexPath *_indexPath;
    NSString *_identifier;
    BOOL _isClone;
    unsigned long long _type;
}

+ (id)collectionItemKeyForLayoutAttributes:(id)attributes;
+ (id)collectionItemKeyForDecorationViewOfKind:(id)kind andIndexPath:(NSIndexPath *)indexPath;
+ (id)collectionItemKeyForSupplementaryViewOfKind:(id)kind andIndexPath:(NSIndexPath *)indexPath;
+ (id)collectionItemKeyForCellWithIndexPath:(NSIndexPath *)indexPath;

@property(readonly, nonatomic) BOOL isClone; // @synthesize isClone=_isClone;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;

- (unsigned long long)hash;
- (void)setType:(unsigned long long)type;
- (void)setIdentifier:(NSString *)identifier;
- (void)setIndexPath:(NSIndexPath *)indexPath;
- (BOOL)isEqual:(id)item;
- (id)copyAsClone:(BOOL)isClone;
- (id)copyWithZone:(struct _NSZone *)zone;
- (NSString *)description;
- (void)dealloc;
- (id)initWithType:(unsigned long long)type indexPath:(NSIndexPath *)indexPath identifier:(NSString *)identifier clone:(BOOL)isClone;
- (id)initWithType:(unsigned long long)type indexPath:(NSIndexPath *)indexPath identifier:(NSString *)identifier;

@end

