//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

#import "UXCollectionViewLayoutProxyDelegate-Protocol.h"

@class NSMapTable, UXCollectionViewLayout;

@interface _UXCollectionViewLayoutProxy : NSProxy
{
    id <UXCollectionViewLayoutProxyDelegate> _delegate;
    UXCollectionViewLayout *_layout;
    NSMapTable *_methodSignituresBySelector;
}

+ (Class)invalidationContextClass;
+ (Class)layoutAttributesClass;
+ (Class)class;
@property(retain, nonatomic) NSMapTable *methodSignituresBySelector; // @synthesize methodSignituresBySelector=_methodSignituresBySelector;
@property(readonly, nonatomic) UXCollectionViewLayout *layout; // @synthesize layout=_layout;
@property(nonatomic) id <UXCollectionViewLayoutProxyDelegate> delegate; // @synthesize delegate=_delegate;
- (id)layoutAttributesForElementsInRect:(CGRect)rect;
- (id)methodSignatureForSelector:(SEL)aSelector;
- (void)forwardInvocation:(id)invocation;
- (Class)class;
- (void)dealloc;
- (id)initWithLayout:(id)layout;

@end

