//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

#import "UXLayoutSupport-Protocol.h"

@class NSLayoutConstraint, NSString;

@interface _UXLayoutGuide : UXView <UXLayoutSupport>

@property(copy, nonatomic) CDUnknownBlockType lengthUpdateBlock;

@property(nonatomic) BOOL horizontal;

@property(nonatomic) CGFloat length;

@end

