//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"
#import "_UXSourceSplitViewDelegate-Protocol.h"

@import  AppKit;

@class NSBox, NSCursor, NSLayoutConstraint, NSString, _UXContainerView;

NS_ASSUME_NONNULL_BEGIN

@interface _UXSourceSplitView : UXView <NSAccessibilityGroup>

@property(nonatomic) __weak id <_UXSourceSplitViewDelegate> _Nullable delegate; // @synthesize delegate=_delegate;

@property(nonatomic) BOOL resizing; // @synthesize resizing=_resizing;
@property(nonatomic) BOOL collapsed; // @synthesize collapsed=_collapsed;

@property(nonatomic) double maximumMasterWidth; // @synthesize maximumMasterWidth=_maximumMasterWidth;
@property(nonatomic) double minimumMasterWidth; // @synthesize minimumMasterWidth=_minimumMasterWidth;

@property(readonly, nonatomic) NSBox * _Nonnull separator; // @synthesize separator=_separator;
@property(readonly, nonatomic) _UXContainerView * _Nonnull detailView; // @synthesize detailView=_detailView;
@property(readonly, nonatomic) _UXContainerView * _Nonnull masterView; // @synthesize masterView=_masterView;

@property(readonly, nonatomic) NSCursor * _Nonnull separatorCursor;

- (void)setCollapsed:(BOOL)collapsed animated:(BOOL)animated completion:(CDUnknownBlockType)completion;

@property(nonatomic) CGFloat masterWidth;

@end

NS_ASSUME_NONNULL_END
