//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSColor;

@interface _UXSinglePixelLine : NSView
{
    NSColor *_color;
}

@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
- (void)cxx_destruct;
- (void)drawRect:(CGRect)rect;
- (void)viewDidChangeBackingProperties;
- (void)viewDidMoveToSuperview;
- (void)updateHeight;

@end

