//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

NS_ASSUME_NONNULL_BEGIN

@interface NSImage (UXKit)
- (NSImage *)resizableImageWithCapInsets:(NSEdgeInsets)capInsets resizingMode:(long long)resizingMode;
- (NSImage *)resizableImageWithCapInsets:(NSEdgeInsets)capInsets;
@end

NS_ASSUME_NONNULL_END

