//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

@class NSColor;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, UXProgressViewStyle) {
    UXProgressViewStyleDefault,
    UXProgressViewStyleBar
};

typedef NS_ENUM(NSInteger, UXActivityIndicatorViewStyle) {
    UXActivityIndicatorViewStyleWhiteLarge,
    UXActivityIndicatorViewStyleWhite,
    UXActivityIndicatorViewStyleGray,
};

@interface NSProgressIndicator (Compatibility)

- (BOOL)isAnimating;

- (void)stopAnimating;

- (void)startAnimating;

@property(retain, nonatomic) NSColor *color;

@property(nonatomic) BOOL hidesWhenStopped;

@property(nonatomic) UXActivityIndicatorViewStyle activityIndicatorViewStyle;

- (void)setProgress:(double)progress animated:(BOOL)animated;

@property(nonatomic) double progress;

@property(nonatomic) UXProgressViewStyle progressViewStyle;

- (id)initWithProgressViewStyle:(UXProgressViewStyle)style;

- (id)initWithActivityIndicatorStyle:(UXActivityIndicatorViewStyle)style;

@end

NS_ASSUME_NONNULL_END

