//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;


@class UXView;

NS_ASSUME_NONNULL_BEGIN

@interface NSResponder (UXKit)

- (BOOL)belongsToViewHierarchy:(UXView *)hierarchy;

@end

NS_ASSUME_NONNULL_END

