//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

NS_ASSUME_NONNULL_BEGIN

@protocol UXScrollViewDelegate;

@interface NSScrollView (UXKit)

@property(nullable,nonatomic,weak) id <UXScrollViewDelegate> delegate;

@property(nonatomic, getter=isScrollEnabled) BOOL scrollEnabled;

@property(nonatomic) BOOL pagingEnabled;

@end

NS_ASSUME_NONNULL_END



