//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;
#import "UITextInputTraits-Protocol.h"

@class NSString;

@interface NSTextView (Compatibility) <UITextInputTraits>

@property(nonatomic) unsigned long long textAlignment;

- (CGSize)sizeThatFits:(CGSize)fitSize;

@property(copy, nonatomic) NSString * _Nullable text;

// Remaining properties

@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) UIReturnKeyType returnKeyType;
@property(nonatomic) UIKeyboardAppearance keyboardAppearance;
@property(nonatomic) UIKeyboardType keyboardType;
@property(nonatomic) UITextSpellCheckingType spellCheckingType;
@property(nonatomic) UITextAutocorrectionType autocorrectionType;
@property(nonatomic) UITextAutocapitalizationType autocapitalizationType;

@end

