//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

#import "UITextInputTraits-Protocol.h"

NS_ASSUME_NONNULL_BEGIN

@class NSString;

@interface NSTextField (Compatibility) <UITextInputTraits>

@property(nonatomic) NSTextAlignment textAlignment;

@property(copy, nonatomic) NSString * _Nullable placeholder;

@property(copy, nonatomic) NSString * _Nullable text;

@property(nonatomic) UITextAutocapitalizationType autocapitalizationType;

@property(nonatomic) UITextAutocorrectionType autocorrectionType;

@property(nonatomic) BOOL enablesReturnKeyAutomatically;

@property(readonly) NSUInteger hash;

@property(nonatomic) UIKeyboardAppearance keyboardAppearance;

@property(nonatomic) UIKeyboardType keyboardType;

@property(nonatomic) UIReturnKeyType returnKeyType;

@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;

@property(nonatomic) UITextSpellCheckingType spellCheckingType;

@end

NS_ASSUME_NONNULL_END


