//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

NS_ASSUME_NONNULL_BEGIN

typedef NSLayoutPriority UILayoutPriority;

@interface NSView (Compatibility)

- (UILayoutPriority)contentHuggingPriorityForAxis:(UILayoutConstraintAxis)axis;

- (void)setContentHuggingPriority:(UILayoutPriority)priority forAxis:(UILayoutConstraintAxis)axis;

- (UILayoutPriority)contentCompressionResistancePriorityForAxis:(UILayoutConstraintAxis)axis;

- (void)setContentCompressionResistancePriority:(UILayoutPriority)priority forAxis:(UILayoutConstraintAxis)axis;

@property(nonatomic) double alpha;

- (BOOL)pointInside:(CGPoint)point withEvent:(NSEvent *)event;

- (void)layoutIfNeeded;

- (void)layoutSubviews;

- (void)setNeedsUpdateConstraints;

- (void)updateConstraintsIfNeeded;

- (void)setNeedsDisplay;

- (void)setNeedsLayout;

- (void)didMoveToWindow;

@end

NS_ASSUME_NONNULL_END

