//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSArray;

@interface NSViewAnimationContext : NSObject

@property(readonly, nonatomic) CDUnknownBlockType completionHandler;
@property(nonatomic) long long animationCount;
@property(retain, nonatomic) NSArray * _Nullable viewAnimations;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

