//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSImage, NSString;

NS_ASSUME_NONNULL_BEGIN

@interface UXBarItem : NSObject

@property(nonatomic) NSInteger tag;

@property(retain, nonatomic) NSImage * _Nullable image;

@property(copy, nonatomic) NSString * _Nullable accessibilityLabel;

@property(retain, nonatomic) NSString * _Nullable title;

@property(nonatomic, getter=isEnabled) BOOL enabled;

@end

NS_ASSUME_NONNULL_END

