//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXBarItem.h"

#import "UXKitAppearance-Protocol.h"

NS_ASSUME_NONNULL_BEGIN

@class NSColor, NSString, NSView, UXViewController;

typedef NS_ENUM(NSInteger, UIBarButtonItemStyle) {
    UIBarButtonItemStylePlain,
    UIBarButtonItemStyleBordered,
    UIBarButtonItemStyleDone,
};

typedef NS_ENUM(NSInteger, UIBarButtonSystemItem) {
    UIBarButtonSystemItemDone,
    UIBarButtonSystemItemCancel,
    UIBarButtonSystemItemEdit,
    UIBarButtonSystemItemSave,
    UIBarButtonSystemItemAdd,
    UIBarButtonSystemItemFlexibleSpace,
    UIBarButtonSystemItemFixedSpace,
    UIBarButtonSystemItemCompose,
    UIBarButtonSystemItemReply,
    UIBarButtonSystemItemAction,
    UIBarButtonSystemItemOrganize,
    UIBarButtonSystemItemBookmarks,
    UIBarButtonSystemItemSearch,
    UIBarButtonSystemItemRefresh,
    UIBarButtonSystemItemStop,
    UIBarButtonSystemItemCamera,
    UIBarButtonSystemItemTrash,
    UIBarButtonSystemItemPlay,
    UIBarButtonSystemItemPause,
    UIBarButtonSystemItemRewind,
    UIBarButtonSystemItemFastForward,
    UIBarButtonSystemItemUndo,
    UIBarButtonSystemItemRedo,
    UIBarButtonSystemItemPageCurl,
};

@interface UXBarButtonItem : UXBarItem <UXKitAppearance>

@property(nonatomic, setter=_setWidthConstrainingItem:, weak) UXBarButtonItem * _Nullable _widthConstrainingItem;

@property(readonly, nonatomic) UIBarButtonSystemItem systemItem;

@property(readonly, nonatomic) UXViewController *contentViewController;

@property(nonatomic) unsigned long long keyEquivalentModifierMask;

@property(retain, nonatomic) NSString * _Nullable keyEquivalent; // @synthesize keyEquivalent=_keyEquivalent;
@property(retain, nonatomic) NSString * _Nullable toolTip; // @synthesize toolTip=_toolTip;
@property(nonatomic, weak) id _Nullable target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(retain, nonatomic) NSView * _Nullable customView; // @synthesize customView=_customView;
@property(nonatomic) CGFloat width; // @synthesize width=_width;
@property(nonatomic) UIBarButtonItemStyle style; // @synthesize style=_style;

- (void)setImage:(NSImage * _Nullable)image;

- (void)setEnabled:(BOOL)enabled;

- (void)setTitle:(NSString * _Nullable)title;

- (id)initWithStyle:(UIBarButtonItemStyle)style target:(id)target action:(SEL)action;

- (id)initWithContentViewController:(NSViewController *)contentVC;

- (id)initWithCustomView:(NSView *)view;

- (id)initWithBarButtonSystemItem:(UIBarButtonSystemItem)systemItem target:(id)target action:(SEL)action;

- (id)initWithTitle:(NSString * _Nullable)title style:(UIBarButtonItemStyle)style target:(id)target action:(SEL)action;

- (id)initWithImage:(NSImage * _Nullable)image style:(UIBarButtonItemStyle)style target:(id)target action:(SEL)action;

@end

NS_ASSUME_NONNULL_END

