//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

@import  AppKit;
#import "UXBarPositioning-Protocol.h"
#import "_UXBarItemsContainer-Protocol.h"
#import "_UXSinglePixelLine.h"

@class NSColor, NSString, _UXSinglePixelLine;

NS_ASSUME_NONNULL_BEGIN

@interface UXBar : UXView <NSAccessibilityGroup, UXBarPositioning>

@property(retain, nonatomic) UXView<_UXBarItemsContainer> *nextItemContainer; // @synthesize nextItemContainer=_nextItemContainer;

@property(nonatomic) CGFloat percent; // @synthesize percent=_percent;

@property(nonatomic) BOOL isInteractiveTransitioning; // @synthesize isInteractiveTransitioning=_isInteractiveTransitioning;

@property(retain, nonatomic) UXView<_UXBarItemsContainer> *barItemsContainer; // @synthesize barItemsContainer=_barItemsContainer;

@property(nonatomic) CGFloat height; // @synthesize height=_height;

@property(nonatomic) CGFloat interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;

@property(retain, nonatomic) NSColor *barTintColor; // @synthesize barTintColor=_barTintColor;

@property(retain, nonatomic) NSColor *borderColor;

@property(nonatomic) BOOL bordered;

@end

NS_ASSUME_NONNULL_END
