//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSString, UXCollectionView, UXCollectionViewLayoutAttributes, UXCollectionViewLayout;

NS_ASSUME_NONNULL_BEGIN

@interface UXCollectionReusableView : NSView

@property(readonly, copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;

- (void)didTransitionFromLayout:(UXCollectionViewLayout *)fromLayout toLayout:(UXCollectionViewLayout *)toLayout;

- (void)willTransitionFromLayout:(UXCollectionViewLayout *)fromLayout toLayout:(UXCollectionViewLayout *)toLayout;

- (void)applyLayoutAttributes:(UXCollectionViewLayoutAttributes *)attributes;

- (BOOL)accessibilityPerformScrollToVisible;

@end

NS_ASSUME_NONNULL_END

