//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;
@class NSIndexPath;

@interface UXCollectionViewUpdateItem : NSObject
{
    NSIndexPath *_initialIndexPath;
    NSIndexPath *_finalIndexPath;
    long long _updateAction;
    id _gap;
}

@property(readonly, nonatomic) long long updateAction; // @synthesize updateAction=_updateAction;
@property(readonly, retain, nonatomic) NSIndexPath *indexPathAfterUpdate; // @synthesize indexPathAfterUpdate=_finalIndexPath;
@property(readonly, retain, nonatomic) NSIndexPath *indexPathBeforeUpdate; // @synthesize indexPathBeforeUpdate=_initialIndexPath;
- (long long)inverseCompareIndexPaths:(id)arg1;
- (long long)compareIndexPaths:(id)arg1;
- (BOOL)_isSectionOperation;
- (void)_setGap:(id)arg1;
- (id)_gap;
- (id)_indexPath;
- (long long)_action;
- (id)description;
- (void)_setNewIndexPath:(NSIndexPath *)arg1;
- (id)_newIndexPath;
- (void)dealloc;
- (id)initWithOldIndexPath:(NSIndexPath *)arg1 newIndexPath:(NSIndexPath *)arg2;
- (id)initWithAction:(long long)arg1 forIndexPath:(NSIndexPath *)arg2;
- (id)initWithInitialIndexPath:(NSIndexPath *)arg1 finalIndexPath:(NSIndexPath *)arg2 updateAction:(long long)arg3;

@end

