//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@import  AppKit;

@class NSIndexPath, NSString;

NS_ASSUME_NONNULL_BEGIN

@interface UXCollectionViewLayoutAttributes : NSObject <NSCopying>

+ (instancetype)layoutAttributesForDecorationViewOfKind:(NSString *)kind withIndexPath:(NSIndexPath *)indexPath;

+ (instancetype)layoutAttributesForSupplementaryViewOfKind:(NSString *)kind withIndexPath:(NSIndexPath *)indexPath;

+ (instancetype)layoutAttributesForCellWithIndexPath:(NSIndexPath *)indexPath;

@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;

@property(nonatomic) BOOL isFloatingPinned; // @synthesize isFloatingPinned=_isFloatingPinned;

@property(nonatomic) CGRect floatingFrame; // @synthesize floatingFrame=_floatingFrame;

@property(nonatomic) BOOL isFloating; // @synthesize isFloating=_isFloating;

@property(nonatomic) long long zIndex; // @synthesize zIndex=_zIndex;

@property(nonatomic) double alpha; // @synthesize alpha=_alpha;

@property(nonatomic) CGSize size; // @synthesize size=_size;

@property(nonatomic) CGPoint center; // @synthesize center=_center;

@property(readonly, nonatomic) NSString *representedElementKind; // @synthesize representedElementKind=_representedElementKind;

@property(readonly, nonatomic) unsigned long long representedElementCategory;

@property(nonatomic) CGRect frame;

@property(nonatomic) CGRect bounds;

@property(nonatomic, getter=isHidden) BOOL hidden;

@end

NS_ASSUME_NONNULL_END

