//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXCollectionReusableView.h"

@class NSView;

NS_ASSUME_NONNULL_BEGIN

@interface UXCollectionViewCell : UXCollectionReusableView

@property(readonly, nonatomic) NSView *contentView;

@property(nonatomic, getter=isSelected) BOOL selected;

@end

NS_ASSUME_NONNULL_END


