//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXViewController.h"

#import "UXCollectionViewDataSource-Protocol.h"
#import "UXCollectionViewDelegate-Protocol.h"

@class NSString, UXCollectionView, UXCollectionViewLayout, UXCollectionViewCell, NSScrollView;

NS_ASSUME_NONNULL_BEGIN

@interface UXCollectionViewController : UXViewController <UXCollectionViewDataSource, UXCollectionViewDelegate>

+ (Class)collectionViewClass;

@property(retain, nonatomic) UXCollectionView *collectionView;

- (double)scrollView:(NSScrollView *)scrollView pageAlignedOriginOnAxis:(NSInteger)axis forProposedDestination:(CGFloat)destination currentOrigin:(CGFloat)currentOrigin initialOrigin:(CGFloat)initialOrigin velocity:(CGFloat)velocity;

- (UXCollectionViewCell *)collectionView:(UXCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath;

- (NSUInteger)collectionView:(UXCollectionView *)collectionView numberOfItemsInSection:(NSUInteger)section;

- (NSUInteger)numberOfSectionsInCollectionView:(UXCollectionView *)collectionView;

- (id)initWithCollectionViewLayout:(UXCollectionViewLayout *)layout;

@end

NS_ASSUME_NONNULL_END


