//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

NS_ASSUME_NONNULL_BEGIN

@interface UXControl : UXView

@property(nonatomic) BOOL ignoresMultiClick;

@property(nonatomic, getter=isEnabled) BOOL enabled;

@property(nonatomic, getter=isSelected) BOOL selected;

@property(nonatomic, getter=isHighlighted) BOOL highlighted;

@property(nonatomic) SEL action;

@property(nonatomic) __weak id _Nullable target;

- (void)setTarget:(id _Nullable)target action:(SEL)action;

- (BOOL)sendAction:(SEL)action to:(id)to;

@end

NS_ASSUME_NONNULL_END

