//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMutableDictionary, NSMutableIndexSet, NSString, UXCollectionView, UXCollectionViewLayoutAccessibility, UXCollectionViewLayoutInvalidationContext;

NS_ASSUME_NONNULL_BEGIN

@interface UXCollectionViewLayout : NSObject

+ (Class)layoutAccessibilityClass;

+ (Class)invalidationContextClass;

+ (Class)layoutAttributesClass;

@property(readonly, nonatomic) UXCollectionViewLayoutAccessibility *layoutAccessibility;

@property(readonly, nonatomic, weak) UXCollectionView * _Nullable collectionView;

- (NSIndexPath * _Nullable)indexPathOfItemBelow:(id)below;

- (NSIndexPath * _Nullable)indexPathOfItemAbove:(id)above;

- (NSIndexPath * _Nullable)indexPathOfItemAfter:(id)after;

- (NSIndexPath * _Nullable)indexPathOfItemBefore:(id)before;

- (NSArray <NSIndexPath *> * _Nullable)indexPathsForItemRangeSelectionFrom:(id)from to:(id)to;

- (NSIndexPath * _Nullable)lastSelectableItemIndexPath;

- (NSIndexPath * _Nullable)firstSelectableItemIndexPath;

- (NSEdgeInsets)insetsForScrollingItemAtIndexPath:(NSIndexPath *)indexPath toScrollPosition:(NSUInteger)position;

- (CGRect)backingAlignedRect:(CGRect)alignedRect options:(NSUInteger)options;

- (NSInteger)userInterfaceLayoutDirection;

- (CGPoint)updatesContentOffsetForProposedContentOffset:(CGPoint)proposedOffset;

- (CGPoint)transitionContentOffsetForProposedContentOffset:(CGPoint)proposedOffset keyItemIndexPath:(NSIndexPath *)indexPath;

- (void)finalizeLayoutTransition;

- (void)prepareForTransitionFromLayout:(UXCollectionViewLayout *)fromLayout;

- (void)prepareForTransitionToLayout:(UXCollectionViewLayout *)toLayout;

- (void)registerNib:(NSNib *)nib forDecorationViewOfKind:(NSString *)kind;

- (void)registerClass:(Class)class forDecorationViewOfKind:(NSString *)kind;

- (id)snapshottedLayoutAttributeForItemAtIndexPath:(NSIndexPath *)indexPath;

- (void)finalizeCollectionViewUpdates;

- (void)prepareForCollectionViewUpdates:(id)updates;

- (CGSize)collectionViewContentSize;

- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedOffset;

- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedOffset withScrollingVelocity:(CGPoint)velocity;

- (id)invalidationContextForBoundsChange:(CGRect)change;

- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)change;

- (BOOL)shouldInvalidateLayoutForScaleFactorChangeFrom:(CGFloat)fromScale to:(CGFloat)toScale;

- (void)invalidateLayoutWithContext:(id)ctx;

- (void)invalidateLayout;

- (void)prepareLayout;

- (UXCollectionViewLayoutAttributes * _Nullable)layoutAttributesForDecorationViewOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes * _Nullable)layoutAttributesForSupplementaryViewOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath;

- (NSArray <UXCollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect;

- (NSArray <NSIndexPath *> * _Nullable)indexPathsToInsertForDecorationViewOfKind:(NSString *)kind;

- (NSArray <NSIndexPath *> * _Nullable)indexPathsToInsertForSupplementaryViewOfKind:(NSString *)kind;

- (NSArray <NSIndexPath *> * _Nullable)indexPathsToDeleteForDecorationViewOfKind:(NSString *)kind;

- (NSArray <NSIndexPath *> * _Nullable)indexPathsToDeleteForSupplementaryViewOfKind:(NSString *)kind;

- (UXCollectionViewLayoutAttributes *)finalLayoutAttributesForDisappearingDecorationElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes *)initialLayoutAttributesForAppearingDecorationElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes *)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes *)initialLayoutAttributesForAppearingSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes *)finalLayoutAttributesForDisappearingItemAtIndexPath:(NSIndexPath *)indexPath;

- (UXCollectionViewLayoutAttributes *)initialLayoutAttributesForAppearingItemAtIndexPath:(NSIndexPath *)indexPath;

- (void)finalizeAnimatedBoundsChange;

- (void)prepareForAnimatedBoundsChange:(CGRect)bounds;

- (NSIndexPath *)proposedDropIndexPathForDraggingPoint:(CGPoint)draggingPoint;

- (NSArray <UXCollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect withIndexPaths:(NSArray <NSIndexPath *> *)indexPaths exchangedWithIndexPaths:(NSArray <NSIndexPath *> *)replacementIndexPaths;

- (NSArray <UXCollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect withIndexPaths:(NSArray <NSIndexPath *> *)indexPaths movedToIndexPath:(NSIndexPath *)indexPath atPoint:(CGPoint)point;

- (NSInteger)dropPositionForPoint:(CGPoint)rect withIndexPaths:(NSArray <NSIndexPath *> *)indexPaths movedToIndexPath:(NSIndexPath *)indexPath;

@end

NS_ASSUME_NONNULL_END

