//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import  AppKit;

@class NSEvent, NSMapTable, UXView;

NS_ASSUME_NONNULL_BEGIN

@interface UXEventTracker : NSResponder

@property(retain, nonatomic) NSMapTable *selectorsByTarget;

@property(copy, nonatomic) CDUnknownBlockType eventTrackerDidEndHandler;

@property(copy, nonatomic) CDUnknownBlockType eventTrackerDidChangeHandler;

@property(copy, nonatomic) CDUnknownBlockType eventTrackerDidBeginHandler;

@property(nonatomic, getter=isEnabled) BOOL enabled;

@property(nonatomic) BOOL cancelsEventsInView;

@property(nonatomic) unsigned long long ignoredModifiers;

@property(nonatomic) CGFloat velocity;

@property(nonatomic) unsigned long long modifiers;

@property(retain, nonatomic) NSEvent *trackingEvent;

@property(nonatomic, weak) UXView * _Nullable view;

@property(nonatomic) NSUInteger state;

- (BOOL)eventTrackerRequiresTouches;

- (void)reset;

@property(readonly, nonatomic) NSUInteger numberOfTouches;

- (CGPoint)locationOfTouch:(NSUInteger)touch inView:(NSView *)view;

- (CGPoint)locationInView:(NSView *)view;

- (void)cancelTracking;

- (void)removeTarget:(id)target;

- (void)addTarget:(id)target action:(SEL)action;

- (id)initWithTarget:(id)target action:(SEL)action;

@end

NS_ASSUME_NONNULL_END

