//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

@import  AppKit;

@class NSImage, NSString;

NS_ASSUME_NONNULL_BEGIN

@interface UXImageView : UXView <NSAccessibilityImage>

@property(retain, nonatomic) NSImage * _Nullable image;

- (void)sizeToFit;

- (instancetype)initWithImage:(NSImage * _Nullable)image;

@end

NS_ASSUME_NONNULL_END

