//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"
@import AppKit;

@class NSImage, NSString;

@interface UXImageView : UXView <NSAccessibilityImage>
{
    double _backingScaleFactor;
    CGSize _proposedSize;
    NSString *accessibilityLabel;
    NSImage *_image;
}

@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel;
- (void)cxx_destruct;
- (void)sizeToFit;
- (void)_updateBackingScaleFactorForWindow:(id)arg1;
- (void)_updateLayerContentsForWindow:(id)arg1;
- (CGSize)_proposedSize;
- (void)_setContentStretchInPixels:(CGRect)arg1 forContentSize:(CGSize)arg2 shouldTile:(BOOL)arg3;
- (void)setFrameSize:(CGSize)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidChangeBackingProperties;
- (CGSize)intrinsicContentSize;
- (id)initWithImage:(NSImage *)arg1;
- (id)initWithFrame:(CGRect)frame;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

