//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

@import  AppKit;

@class NSAttributedString, NSColor, NSFont, NSString, NSTextField;

NS_ASSUME_NONNULL_BEGIN

@interface UXLabel : UXView <NSAccessibilityStaticText>

@property(nonatomic, getter=isHighlighted) BOOL highlighted;

@property(retain, nonatomic) NSColor * _Nullable highlightedTextColor;

@property(nonatomic) long long numberOfLines;

@property(nonatomic) CGSize shadowOffset;

@property(retain, nonatomic) NSColor * _Nullable shadowColor;

@property(retain, nonatomic) NSColor *textColor;

- (NSCell *)textFieldCell;

@property(nonatomic) BOOL selectable;

@property(nonatomic) BOOL centerVertically;

@property(nonatomic) CGFloat preferredMaxLayoutWidth;

@property(nonatomic) NSTextAlignment textAlignment;

@property(nonatomic) NSLineBreakMode lineBreakMode;

@property(copy, nonatomic) NSAttributedString * _Nullable attributedText;

@property(copy, nonatomic) NSString * _Nullable text;

@property(retain, nonatomic) NSFont * _Nullable font;

- (void)sizeToFit;

- (CGSize)sizeThatFits:(CGSize)fitSize;

@end

NS_ASSUME_NONNULL_END

