//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSArray, NSMutableArray, NSString, NSView, UXBarButtonItem, UXLabel;

NS_ASSUME_NONNULL_BEGIN

@interface UXNavigationItem : NSObject

@property(retain) NSMutableArray <UXBarButtonItem *> * _Nullable childItems;

@property(nonatomic) BOOL leftItemsSupplementBackButton;

@property(retain, nonatomic) NSArray <UXBarButtonItem *> * _Nullable rightBarButtonItems;

@property(nonatomic) BOOL hidesAlternateTitleView;

@property(nonatomic) BOOL hidesBackButton;

@property(copy, nonatomic) NSString * _Nullable prompt;

@property(retain, nonatomic) NSView * _Nullable titleView;

- (void)removeChildItem:(UXNavigationItem *)childItem;

- (void)addChildItem:(UXNavigationItem *)childItem;

@property(retain, nonatomic) UXBarButtonItem * _Nullable rightBarButtonItem;

@property(retain, nonatomic) NSArray <UXBarButtonItem *> * _Nullable leftBarButtonItems;

@property(retain, nonatomic) UXBarButtonItem * _Nullable leftBarButtonItem;

@property(retain, nonatomic) NSString * _Nullable title;

@property(readonly, nonatomic) UXLabel * _Nullable internalTitleView;

@property(retain, nonatomic) NSArray <UXBarButtonItem *> * _Nullable trailingBarButtonItems;

- (void)setTrailingBarButtonItems:(NSArray <UXBarButtonItem *> *)trailingItems animated:(BOOL)animated;

@property(retain, nonatomic) NSArray <UXBarButtonItem *> * _Nullable leadingBarButtonItems;

- (void)setLeadingBarButtonItems:(NSArray <UXBarButtonItem *> *)leadingItems animated:(BOOL)animated;

- (void)setRightBarButtonItems:(NSArray <UXBarButtonItem *> *)rightItems animated:(BOOL)animated;

- (void)setRightBarButtonItem:(UXBarButtonItem * _Nullable)rightItem animated:(BOOL)animated;

- (void)setLeftBarButtonItems:(NSArray <UXBarButtonItem *> *)leftItems animated:(BOOL)animated;

- (void)setLeftBarButtonItem:(UXBarButtonItem * _Nullable)leftItem animated:(BOOL)animated;

- (instancetype)initWithTitle:(NSString * _Nullable)title;

@end

NS_ASSUME_NONNULL_END
