//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXViewController.h"

#import "UXToolbarDelegate-Protocol.h"
//#import "_UXAccessoryBarContainer-Protocol.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, NSString, UXEventTracker, UXNavigationBar, UXToolbar, UXTransitionController, _UXContainerView, _UXViewControllerOneToOneTransitionContext;

NS_ASSUME_NONNULL_BEGIN

@interface UXNavigationController : UXViewController <UXToolbarDelegate>

+ (id)keyPathsForValuesAffectingPreferredContentSize;

@property(retain, nonatomic) UXViewController *provisionalPreviousViewController;

@property(nonatomic, weak) UXViewController * _Nullable observedViewController;

@property(retain, nonatomic) UXTransitionController *defaultTransitionController;

@property(nonatomic) NSInteger currentOperation;

@property(retain, nonatomic) _UXViewControllerOneToOneTransitionContext *currentTransitionContext;

@property(retain, nonatomic) NSArray *topViewControllerOtherConstraints;

@property(retain, nonatomic) NSLayoutConstraint *topViewControllerLeftConstraint;

@property(retain, nonatomic) NSLayoutConstraint *toolbarLeftConstraint;

@property(retain, nonatomic) NSLayoutConstraint *toolbarVerticalConstraint;

@property(retain, nonatomic) NSArray <NSLayoutConstraint *> *navigationBarConstraints;

@property(retain, nonatomic) NSLayoutConstraint *navigationBarTopConstraint;

@property(retain, nonatomic) NSLayoutConstraint *bottomConstraint;

@property(retain, nonatomic) NSLayoutConstraint *topConstraint;

@property(retain, nonatomic) NSMutableArray <NSLayoutConstraint *> *addedConstraints;

@property(retain, nonatomic) _UXContainerView *containerView;

@property(retain, nonatomic) NSMutableArray *internalViewControllers;

@property(readonly, nonatomic) BOOL isInteractive;

@property(readonly, nonatomic) BOOL isTransitioning;

@property(nonatomic, setter=_setBackBarButtonItemBordered:) BOOL _backBarButtonItemBordered;

@property(nonatomic, setter=_setHidesBackTitles:) BOOL _hidesBackTitles;

@property(nonatomic, setter=_setDefaultPopTransition:) unsigned long long _defaultPopTransition;

@property(nonatomic, setter=_setDefaultPushTransition:) unsigned long long _defaultPushTransition;

@property(nonatomic, setter=_setToolbarPosition:) long long _toolbarPosition;

@property(nonatomic, setter=_setLeftContentInset:) double _leftContentInset;

@property(nonatomic, getter=_isLocked, setter=_setLocked:) BOOL _locked;

@property(nonatomic, getter=_isFullScreenMode, setter=_setFullScreenMode:) BOOL _fullScreenMode;

@property(readonly, nonatomic) UXEventTracker *interactivePopEventTracker;

@property(nonatomic, weak) id <UXNavigationControllerDelegate> _Nullable delegate;

@property(nonatomic, getter=isToolbarHidden) BOOL toolbarHidden;

@property(nonatomic, getter=isNavigationBarDetached) BOOL navigationBarDetached;

@property(nonatomic, getter=isNavigationBarHidden) BOOL navigationBarHidden;

- (NSInteger)positionForBar:(UXNavigationBar *)bar;

- (nullable NSArray<__kindof NSViewController *> *)popToViewController:(NSViewController *)viewController animated:(BOOL)animated;

- (nullable NSArray<__kindof NSViewController *> *)popToRootViewControllerAnimated:(BOOL)animated;

- (nullable NSArray<__kindof NSViewController *> *)popViewControllerAnimated:(BOOL)animated;

- (void)pushViewController:(NSViewController *)viewController animated:(BOOL)animated;

- (NSViewController * _Nullable)visibleViewController;

- (NSViewController * _Nullable)topViewController;

- (void)setViewControllers:(NSArray <NSViewController *> *)viewControllers animated:(BOOL)animated;

- (void)detachNavigationBar;

@property(readonly, nonatomic) UXToolbar *toolbar;

@property(readonly, nonatomic) UXToolbar *accessoryBar;

@property(readonly, nonatomic, getter=isAccessoryBarHidden) BOOL accessoryBarHidden;

@property(readonly, nonatomic) UXNavigationBar *navigationBar;

- (void)setToolbarHidden:(BOOL)hidden animated:(BOOL)animated;

- (void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated;

@property(copy, nonatomic) NSArray<__kindof NSViewController *> *viewControllers;

- (void)setEdgesForExtendedLayout:(NSUInteger)edges;

- (id)transitionCoordinator;

- (void)invalidateIntrinsicLayoutInsets;

- (NSEdgeInsets)intrinsicLayoutInsets;

- (CGSize)preferredContentSize;

- (instancetype)initWithRootViewController:(NSViewController *)viewController;

@end

NS_ASSUME_NONNULL_END
