//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXBar.h"
#import "UXNavigationControllerDelegate-Protocol.h"

@class NSArray, NSImage, NSMutableArray, NSView, UXNavigationItem, _UXNavigationItemContainerView;

NS_ASSUME_NONNULL_BEGIN

@interface UXNavigationBar : UXBar

@property(nonatomic) BOOL recalculatingWindowKeyViewLoop;

@property(retain, nonatomic) UXNavigationItem *transitioningItem;

@property(nonatomic) NSInteger currentOperation;

@property(retain, nonatomic) _UXNavigationItemContainerView *topItemContainer;

@property(retain, nonatomic) NSMutableArray *internalItems;

@property(nonatomic) CGFloat centerYOffset;

@property(nonatomic) CGFloat rightInteritemSpacing;

@property(nonatomic) CGFloat leftInteritemSpacing;

@property(nonatomic, getter=isDetached) BOOL detached;

@property(nonatomic) BOOL enableAlernateTitle;

@property(retain, nonatomic) NSView * _Nullable alternateTitleView;

@property(retain, nonatomic) NSImage * _Nullable backIndicatorImage;

@property(copy, nonatomic) NSArray <UXNavigationItem *> * _Nullable items; // @synthesize items=_items;

@property(nonatomic, weak) NSView * _Nullable titleCenteringTrackedView;

@property(nonatomic) NSEdgeInsets edgeInsets;

@property(nonatomic, getter=isTranslucent) BOOL translucent;

@property(nonatomic, weak) id <UXNavigationBarDelegate> _Nullable delegate;

- (void)setNeedsRecalcuateWindowKeyViewLoop;

- (void)recalculateKeyViewLoop;

- (void)beginInteractivePop;

- (void)beginInteractivePushToItem:(UXNavigationItem *)item;

- (id)popNavigationItemAnimated:(BOOL)animated;

- (void)pushNavigationItem:(UXNavigationItem *)item animated:(BOOL)animated;

@property(readonly, nonatomic) UXNavigationItem *backItem;

@property(readonly, nonatomic) UXNavigationItem *topItem;

@end

NS_ASSUME_NONNULL_END

