//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class UXNavigationController, UXViewController;

NS_ASSUME_NONNULL_BEGIN

@protocol UXNavigationControllerDelegate <NSObject>

@optional

- (BOOL)navigationController:(UXNavigationController *)navigationController shouldBeginInteractivePopFromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;

- (id <UXViewControllerAnimatedTransitioning>)navigationController:(UXNavigationController *)navigationController animationControllerForOperation:(NSInteger)operation fromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;

- (id <UXViewControllerInteractiveTransitioning>)navigationController:(UXNavigationController *)navigationController interactionControllerForAnimationController:(id <UXViewControllerAnimatedTransitioning>)animagionController;

- (void)navigationController:(UXNavigationController *)navigationController didShowViewController:(UXViewController *)viewController;

- (void)navigationController:(UXNavigationController *)navigationController willShowViewController:(UXViewController *)viewController;

@end

NS_ASSUME_NONNULL_END
