//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXTransitionController.h"

@class UXView;

@interface UXParallaxTransitionController : UXTransitionController
{
    UXView *_dimmingView;
}

+ (void)_addShadowToView:(NSView *)view withAlpha:(CGFloat)alpha;

@end

