//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXTransitionController.h"

@class UXView;

@interface UXParallaxTransitionController : UXTransitionController
{
    UXView *_dimmingView;
}

+ (void)_addShadowToview:(NSView *)arg1 withAlpha:(double)arg2;
- (void)cxx_destruct;
- (BOOL)navigationController:(id)arg1 shouldBeginInteractivePopFromViewController:(UXViewController *)arg2 toViewController:(UXViewController *)arg3;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(UXViewController *)arg3 toViewController:(UXViewController *)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (void)_setupDimmingViewInContext:(id)arg1 withAlpha:(double)arg2;
- (void)updateInteractiveTransition:(double)arg1 inContext:(id)arg2;
- (void)startInteractiveTransition:(id)arg1;
- (void)animateTransition:(id)arg1;

@end

