//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXViewController.h"

#import "UXNavigationControllerDelegate-Protocol.h"
#import "_UXSourceSplitViewDelegate-Protocol.h"

@class NSArray, NSMapTable, NSOperationQueue, NSSegmentedControl, NSString, NSView, UXTransitionController, _UXSourceSplitView, _UXViewControllerOneToOneTransitionContext, UXNavigationController;
@protocol UXSourceList;

NS_ASSUME_NONNULL_BEGIN

@interface UXSourceController : UXViewController <UXNavigationControllerDelegate, _UXSourceSplitViewDelegate>

@property(readonly) NSOperationQueue *viewControllerOperations;

@property(readonly, nonatomic) NSMapTable *transitionControllerClassByToViewControllerClass;

@property(readonly, nonatomic) NSMapTable *navigationControllerByRootViewController;

@property(readonly, nonatomic) _UXSourceSplitView *splitView;

@property(readonly, nonatomic) NSSegmentedControl *segmentedControl;

@property(copy, nonatomic) NSString * _Nullable sourceListAutosaveName;

@property(retain, nonatomic) UXViewController <UXSourceList> *sourceListViewController;

@property(retain, nonatomic) UXViewController *selectedViewController;

@property(copy, nonatomic) NSArray <UXViewController *> *rootViewControllers;

@property(nonatomic) NSInteger style;

@property(nonatomic) NSInteger preferredStyle;

- (id)transitionCoordinator;

- (void)dismissViewControllerAnimated:(BOOL)animated completion:(void (^ __nullable)(void))completion;

- (void)presentViewController:(UXViewController *)vc animated:(BOOL)animated completion:(void (^ __nullable)(void))completion;

- (void)removeDestination:(id <UXNavigationDestination>)destination animated:(BOOL)animated completion:(void (^ __nullable)(void))completion;

- (void)navigateToDestination:(id <UXNavigationDestination>)destination animated:(BOOL)animated completion:(void (^ __nullable)(void))completion;

- (void)didChangeSelectedViewController;

- (void)willAddNavigationController:(UXNavigationController *)navigationController;

- (void)segmentChanged:(id)change;

@property(nonatomic) unsigned long long selectedIndex;

- (void)setSelectedIndex:(NSUInteger)index animated:(BOOL)animated;

- (void)setSelectedViewController:(UXViewController *)selectedViewController animated:(BOOL)animated;

- (void)setRootViewControllers:(NSArray <UXViewController *> *)rootViewControllers destination:(id <UXNavigationDestination>)destination completion:(void (^ __nullable)(void))completion;

@property(readonly, nonatomic) BOOL alternateTitleEnabled;

- (id)tabBarView;

- (void)unregisterTransitionControllerForTransitionToViewControllerClass:(Class)toVCClass;

- (void)registerTranistionControllerClass:(Class)transitionClass forViewControllerClass:(Class)viewControllerClass;

- (void)registerTransitionControllerClass:(Class)transitionClass forViewControllerClass:(Class)viewControllerClass;

- (id <UXNavigationDestination>)destinationForNavigationIdentifier:(NSString *)identifier title:(NSString *)title;

- (id <UXNavigationDestination>)destinationForViewController:(UXViewController *)viewController;

- (void)unregisterTransitoryViewController:(UXViewController *)transitoryViewController;

- (void)registerTransitoryViewController:(UXViewController *)transitoryViewController;

@property(readonly, nonatomic) id <UXNavigationDestination> currentNavigationDestination;

- (void)removeRootViewControllerAtIndex:(NSInteger)index;

- (void)insertRootViewController:(NSViewController *)rootViewController atIndex:(NSInteger)index;

- (void)addRootViewController:(NSViewController *)rootViewController;

@end

NS_ASSUME_NONNULL_END
