//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXBarItem.h"

@class NSSet;

NS_ASSUME_NONNULL_BEGIN

@interface UXTabBarItem : UXBarItem

@property(copy, nonatomic) NSSet *possibleTitles;

- (instancetype)initWithTitle:(NSString * _Nullable)arg1;

@end

NS_ASSUME_NONNULL_END

