//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXCollectionViewFlowLayout.h"

@class NSMutableArray, NSMutableDictionary;

NS_ASSUME_NONNULL_BEGIN

@interface UXTableLayout : UXCollectionViewFlowLayout

@property(readonly, nonatomic) NSMutableDictionary<NSIndexPath *,UXCollectionViewLayoutAttributes *> *headerAttributesByIndexPath;

@property(readonly, nonatomic) NSMutableArray <UXCollectionViewLayoutAttributes *>  *layoutAttributesArray;

- (NSEdgeInsets)insetForSection:(NSEdgeInsets)section;

@property(nonatomic) BOOL showsSectionFooterForSingleSection;

@property(nonatomic) BOOL showsSectionHeaderForSingleSection;

@property(nonatomic) BOOL floatingHeadersDisabled;

@end

NS_ASSUME_NONNULL_END

