//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXCollectionView.h"
#import "UXTableView.h"
#import "UXCollectionViewDataSource-Protocol.h"

@class NSColor, NSIndexPath, NSMenu, UXCollectionView, UXCollectionViewLayout;

@interface UXTableView : UXCollectionView
{
    struct {
        unsigned int delegateImplementsTitleForHeaderInSection:1;
        unsigned int delegateImplementsTitleForFooterInSection:1;
        unsigned int delegateImplementsHeaderViewForSection:1;
        unsigned int delegateImplementsFooterViewForSection:1;
        unsigned int delegateImplementsHeightForHeaderInSection:1;
        unsigned int delegateImplementsHeightForRowAtIndexPath:1;
        unsigned int delegateImplementsDidSelectionRowAtIndexPath:1;
        unsigned int delegateImplementsShouldHighlightRowAtIndexPath:1;
        unsigned int delegateImplementsDidHighlightRowAtIndexPath:1;
        unsigned int delegateImplementsDidUnhighlightRowAtIndexPath:1;
        unsigned int delegateImplementsEditingStyleForRowAtIndexPath:1;
        unsigned int delegateImplementsDidDeselectRowAtIndexPath:1;
    } _tableViewDelegateFlags;
    struct {
        unsigned int dataSourceImplementsNumberOfSectionsInTableView:1;
        unsigned int dataSourceImplementsCanEditRowAtIndexPath:1;
        unsigned int dataSourceImplementsCommitEditingStyleForRowAtIndexPath:1;
    } _tableViewDataSourceFlags;
    NSIndexPath *_highlightedIndexPath;
    NSMenu *_observedMenu;
    BOOL __floatingHeadersDisabled;
    id <UXTableViewDataSource> _tableViewDataSource;
    id <UXTableViewDelegate> _tableViewDelegate;
    double _rowHeight;
    long long _separatorStyle;
    NSColor *_separatorColor;
    NSEdgeInsets _separatorInset;
}

+ (unsigned long long)collectionViewScrollPositionFromScrollPosition:(long long)arg1;
+ (Class)documentClass;

@property(nonatomic, setter=_setFloatingHeadersDisabled:) BOOL _floatingHeadersDisabled; // @synthesize _floatingHeadersDisabled=__floatingHeadersDisabled;
@property(nonatomic) NSEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
@property(copy, nonatomic) NSColor *separatorColor; // @synthesize separatorColor=_separatorColor;
@property(nonatomic) long long separatorStyle; // @synthesize separatorStyle=_separatorStyle;
@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
@property(nonatomic) __weak id <UXTableViewDelegate> tableViewDelegate; // @synthesize tableViewDelegate=_tableViewDelegate;
@property(nonatomic) __weak id <UXTableViewDataSource> tableViewDataSource; // @synthesize tableViewDataSource=_tableViewDataSource;

- (void)cxx_destruct;

@property(nonatomic) double alpha;

- (void)_checkForAccessoryViewsInScrollerAreas;
- (void)collectionView:(UXCollectionView *)collectionView layout:(UXCollectionViewLayout *)layout supplementaryViewDidEndFloatingAtIndexPath:(NSIndexPath *)indexPath kind:(id)arg4;
- (void)collectionView:(UXCollectionView *)collectionView layout:(UXCollectionViewLayout *)layout supplementaryViewDidBeginFloatingAtIndexPath:(NSIndexPath *)indexPath kind:(id)arg4;
- (CGSize)collectionView:(UXCollectionView *)collectionView layout:(UXCollectionViewLayout *)layout sizeForItemAtIndexPath:(NSIndexPath *)indexPath;
- (CGSize)collectionView:(UXCollectionView *)collectionView layout:(UXCollectionViewLayout *)layout referenceSizeForFooterInSection:(long long)arg3;
- (CGSize)collectionView:(UXCollectionView *)collectionView layout:(UXCollectionViewLayout *)layout referenceSizeForHeaderInSection:(long long)arg3;
- (void)collectionView:(UXCollectionView *)collectionView itemWasRightClickedAtIndexPath:(NSIndexPath *)indexPath withEvent:(id)arg3;
- (long long)numberOfSectionsInCollectionView:(UXCollectionView *)collectionView;
- (id)collectionView:(UXCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath;
- (long long)collectionView:(UXCollectionView *)collectionView numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(UXCollectionView *)collectionView viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(NSIndexPath *)indexPath;
- (void)deleteWordBackward:(id)arg1;
- (void)moveRight:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (id)menuForEvent:(id)arg1;
- (void)_menuDidEndTracking:(id)arg1;
- (void)_menuDidBeginTracking:(id)arg1;
- (void)deselectRowAtIndexPath:(NSIndexPath *)indexPath animated:(BOOL)arg2;
- (void)selectRowAtIndexPath:(NSIndexPath *)indexPath animated:(BOOL)arg2 scrollPosition:(long long)arg3;
- (id)indexPathForSelectedRow;
- (id)indexPathForClickedRow;
- (void)moveRowAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)indexPath;
- (void)reloadRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)deleteRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)insertRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)deleteSections:(id)arg1 withRowAnimation:(long long)arg2;
- (void)insertSections:(id)arg1 withRowAnimation:(long long)arg2;
- (void)endUpdates;
- (void)beginUpdates;
- (id)indexPathsForVisibleRows;
- (void)sizeToFit;
- (CGSize)sizeThatFits:(CGSize)size;
- (long long)numberOfRowsInSection:(long long)section;
- (id)dequeueReusableHeaderFooterViewWithReuseIdentifier:(NSString *)reuseIdentifier forSection:(long long)arg2;
- (UXTableViewCell *)dequeueReusableCellWithReuseIdentifier:(NSString *)reuseIdentifier forIndexPath:(NSIndexPath *)indexPath;
- (UXTableViewCell *)dequeueReusableCellWithIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath *)indexPath;
- (void)registerClass:(Class)aClass forCellReuseIdentifier:(NSString *)reuseIdentifier;
- (id)cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)setDelegate:(__weak id <UXTableViewDelegate>)delegate;
- (void)setDataSource:(__weak id <UXTableViewDataSource>)dataSource;
- (BOOL)overdrawEnabled;
- (void)setOverdrawEnabled:(BOOL)overdrawEnabled;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(CGRect)frame;
- (id)initWithFrame:(CGRect)frame style:(long long)style;
- (id)initWithFrame:(CGRect)frame collectionViewlayout:(UXCollectionViewLayout *)layout;
- (void)setNeedsDisplay:(BOOL)arg1;
@property(nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;

@end

