//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXCollectionViewController.h"
#import "UXTableView.h"

@class UXTableView;

NS_ASSUME_NONNULL_BEGIN

@interface UXTableViewController : UXCollectionViewController

+ (Class)collectionViewClass;

- (id)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil;

- (id)initWithStyle:(UITableViewStyle)style;

@property(readonly, nonatomic) id <UXTableViewDelegate> tableViewDelegate;

@property(readonly, nonatomic) UXTableView *tableView;

@end


NS_ASSUME_NONNULL_END
