//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import "UXViewControllerAnimatedTransitioning-Protocol.h"
#import "UXViewControllerInteractiveTransitioning-Protocol.h"

@class NSString, UXNavigationController;

NS_ASSUME_NONNULL_BEGIN

@interface UXTransitionController : NSObject <UXViewControllerAnimatedTransitioning, UXViewControllerInteractiveTransitioning>

@property(readonly, nonatomic) CGFloat percentComplete;

@property(nonatomic) NSUInteger operation; // @synthesize operation=_operation;

- (BOOL)navigationController:(UXNavigationController *)navigationController shouldBeginInteractivePopFromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;

- (id)navigationController:(UXNavigationController *)navigationController animationControllerForOperation:(NSInteger)operation fromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;

- (id)navigationController:(UXNavigationController *)navigationController interactionControllerForAnimationController:(id)animationController;

- (void)animateTransition:(id)transition;

- (CGFloat)transitionDuration:(id)transition;

- (void)updateInteractiveTransition:(CGFloat)transition inContext:(id)context;

- (void)startInteractiveTransition:(id)transition;

@end

NS_ASSUME_NONNULL_END

