//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@interface UXViewAnimationContext : NSObject

@property(nonatomic) CGFloat velocity;

@property(nonatomic) CGFloat damping;

@property(nonatomic) CGFloat stiffness;

@property(nonatomic) CGFloat mass;

- (void)generateSpringPropertiesForDuration:(CGFloat)duration damping:(CGFloat)damping velocity:(CGFloat)velocity;

@end

