//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXViewControllerTransitionCoordinatorContext-Protocol.h"

@class UXView;

@protocol UXViewControllerTransitionCoordinator <UXViewControllerTransitionCoordinatorContext>

- (void)notifyWhenInteractionEndsUsingBlock:(void (^)(id <UXViewControllerTransitionCoordinatorContext>))block;

- (BOOL)animateAlongsideTransitionInView:(UXView *)view animation:(void (^)(id <UXViewControllerTransitionCoordinatorContext>))animation completion:(void (^)(id <UXViewControllerTransitionCoordinatorContext>))completion;

- (BOOL)animateAlongsideTransition:(void (^)(id <UXViewControllerTransitionCoordinatorContext>))transition completion:(void (^)(id <UXViewControllerTransitionCoordinatorContext>))completion;

@end

