//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSString, UXView, UXViewController;

NS_ASSUME_NONNULL_BEGIN

@protocol UXViewControllerContextTransitioning <NSObject>

- (CGRect)finalFrameForViewController:(UXViewController *)viewController;

- (CGRect)initialFrameForViewController:(UXViewController *)viewController;

- (UXViewController * _Nullable)viewControllerForKey:(NSString *)key;

- (void)completeTransition:(BOOL)animated;

- (void)cancelInteractiveTransition;

- (void)finishInteractiveTransition;

- (void)updateInteractiveTransition:(CGFloat)progress;

- (long long)presentationStyle;

- (BOOL)transitionWasCancelled;

- (BOOL)isInteractive;

- (BOOL)isAnimated;

- (UXView *)containerView;

@end

NS_ASSUME_NONNULL_END

