//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXViewControllerContextTransitioning-Protocol.h"

NS_ASSUME_NONNULL_BEGIN

@protocol UXViewControllerAnimatedTransitioning <NSObject>

- (void)animateTransition:(id <UXViewControllerContextTransitioning>)transition;

- (double)transitionDuration:(id <UXViewControllerContextTransitioning>)transition;

@optional

- (void)animationEnded:(BOOL)animated;

@end

NS_ASSUME_NONNULL_END

