//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSWindow, UXWindowController;

NS_ASSUME_NONNULL_BEGIN

@interface UXViewControllerWindowTransition : NSViewControllerPresentationAnimatorObject

@property(retain) UXWindowController *windowController;

- (void)animateDismissalOfViewController:(NSViewController *)viewController fromViewController:(NSViewController *)fromViewController;

- (void)animatePresentationOfViewController:(NSViewController *)presentingViewController fromViewController:(NSViewController *)fromViewController;

@property(readonly) NSWindow *window;

@end

NS_ASSUME_NONNULL_END
