//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"
#import "UXViewController.h"
@class NSString;

NS_ASSUME_NONNULL_BEGIN

@protocol UXViewControllerTransitionCoordinatorContext <NSObject>

- (UXView *)containerView;

- (UXViewController * _Nullable)viewControllerForKey:(NSString *)arg1;

- (UIViewAnimationCurve)completionCurve;

- (double)completionVelocity;

- (double)percentComplete;

- (double)transitionDuration;

- (BOOL)isCancelled;

- (BOOL)isInteractive;

- (BOOL)initiallyInteractive;

- (UIModalPresentationStyle)presentationStyle;

- (BOOL)isAnimated;

@end

NS_ASSUME_NONNULL_END

