//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSString, NSTitlebarAccessoryViewController, NSToolbarItem, UXToolbar, UXViewController, _UXWindow, UXNavigationController;

NS_ASSUME_NONNULL_BEGIN

@interface UXWindowController : NSWindowController <NSToolbarDelegate, NSWindowDelegate>

+ (instancetype)defaultWindow;

@property NSToolbarItem * _Nullable navigationBarToolbarItem;

- (void)windowDidBecomeFirstResponder:(id)notification;

- (void)windowDidRecalculateKeyViewLoop:(id)notification;

- (void)windowWillRecalculateKeyViewLoop:(id)notification;

- (CGRect)window:(_UXWindow *)window willPositionSheet:(NSWindow *)sheet usingRect:(CGRect)rect;

- (UXNavigationController * _Nullable)rootNavigationController;

@property(retain, nonatomic) UXViewController * _Nullable rootViewController;

@property(readonly, nonatomic) NSTitlebarAccessoryViewController * _Nullable titlebarAccessoryViewController;

- (void)teardownViewControllerHierarchy;

- (id)initWithWindow:(_UXWindow *)window;

- (id)initWithRootViewController:(UXViewController *)rootViewController;

@end

NS_ASSUME_NONNULL_END

